import { NiboValue, ChocolateEntry, MeetingEdition } from "../types";

export const NIBO_VALUES: NiboValue[] = [
  {
    id: 1,
    title: "Nosso cliente vem em primeiro lugar",
    shortName: "Cliente em 1º Lugar",
    description: "Foco obsessivo no sucesso, experiência e solução das dores do cliente.",
    color: "#0284c7", // Sky blue
    badgeBg: "bg-sky-50 text-sky-700 border-sky-200",
    badgeBorder: "border-sky-500",
    iconName: "Users",
  },
  {
    id: 2,
    title: "Sonhamos grande",
    shortName: "Sonhamos Grande",
    description: "Ambição, visão de futuro e coragem para transformar o mercado.",
    color: "#8b5cf6", // Violet
    badgeBg: "bg-purple-50 text-purple-700 border-purple-200",
    badgeBorder: "border-purple-500",
    iconName: "Sparkles",
  },
  {
    id: 3,
    title: "Execução enérgica, focada e lean",
    shortName: "Execução Lean & Focada",
    description: "Agilidade, disciplina, simplicidade e foco no que realmente gera impacto.",
    color: "#e11d48", // Rose
    badgeBg: "bg-rose-50 text-rose-700 border-rose-200",
    badgeBorder: "border-rose-500",
    iconName: "Zap",
  },
  {
    id: 4,
    title: "Produtos que emocionam nossos clientes",
    shortName: "Produtos que Emocionam",
    description: "Qualidade estética, funcionalidade impecável e paixão em cada detalhe.",
    color: "#ea580c", // Orange
    badgeBg: "bg-orange-50 text-orange-700 border-orange-200",
    badgeBorder: "border-orange-500",
    iconName: "Heart",
  },
  {
    id: 5,
    title: "Aprendemos e melhoramos todos os dias",
    shortName: "Melhoria Contínua",
    description: "Curiosidade intelectual, busca por feedback e evolução constante.",
    color: "#059669", // Emerald
    badgeBg: "bg-emerald-50 text-emerald-700 border-emerald-200",
    badgeBorder: "border-emerald-500",
    iconName: "TrendingUp",
  },
  {
    id: 6,
    title: "Tomamos iniciativa e não temos medo de errar",
    shortName: "Iniciativa & Coragem",
    description: "Autonomia com responsabilidade, ousadia para testar e aprender rápido.",
    color: "#d97706", // Amber
    badgeBg: "bg-amber-50 text-amber-700 border-amber-200",
    badgeBorder: "border-amber-500",
    iconName: "Flame",
  },
  {
    id: 7,
    title: "Somos humildes",
    shortName: "Humildade",
    description: "Abertura para ouvir, respeito mútuo, sem ego e sempre dispostos a ajudar.",
    color: "#0d9488", // Teal
    badgeBg: "bg-teal-50 text-teal-700 border-teal-200",
    badgeBorder: "border-teal-500",
    iconName: "ShieldCheck",
  },
  {
    id: 8,
    title: "Profissionais A+, uma equipe A+++",
    shortName: "Profissionais A+ / Equipe A+++",
    description: "Excelência técnica, colaboração de alto nível e padrão elevado.",
    color: "#4f46e5", // Indigo
    badgeBg: "bg-indigo-50 text-indigo-700 border-indigo-200",
    badgeBorder: "border-indigo-500",
    iconName: "Award",
  },
  {
    id: 9,
    title: "Nos divertimos enquanto fazemos tudo isso",
    shortName: "Diversão & Leveza",
    description: "Celebração das conquistas, bom humor, entusiasmo e companheirismo.",
    color: "#db2777", // Pink
    badgeBg: "bg-pink-50 text-pink-700 border-pink-200",
    badgeBorder: "border-pink-500",
    iconName: "Smile",
  },
];

export const INITIAL_EDITIONS: MeetingEdition[] = [
  {
    id: "edition-2026-08",
    name: "Reunião Geral Nibo - Agosto/2026",
    monthYear: "Agosto/2026",
    date: "2026-08-20",
    status: "active",
  },
  {
    id: "edition-2026-07",
    name: "Reunião Geral Nibo - Julho/2026",
    monthYear: "Julho/2026",
    date: "2026-07-16",
    status: "completed",
  },
  {
    id: "edition-2026-06",
    name: "Reunião Geral Nibo - Junho/2026",
    monthYear: "Junho/2026",
    date: "2026-06-18",
    status: "completed",
  },
  {
    id: "edition-2026-05",
    name: "Reunião Geral Nibo - Maio/2026",
    monthYear: "Maio/2026",
    date: "2026-05-21",
    status: "completed",
  },
];

export const INITIAL_ENTRIES: ChocolateEntry[] = [
  // --- AGOSTO 2026 (ATUAL) ---
  {
    id: "entry-1",
    order: 1,
    editionId: "edition-2026-08",
    giver: "Kelvin",
    receiver: "Time Automação Contábil",
    valueIds: [3, 8],
    notes: "Pela entrega incrível da sprint e suporte impecável aos contadores parceiros!",
    status: "entregue",
    createdAt: "2026-08-20T10:00:00Z",
    presentedAt: "2026-08-20T11:05:00Z",
  },
  {
    id: "entry-2",
    order: 2,
    editionId: "edition-2026-08",
    giver: "Breno",
    receiver: "Roberta Rocha",
    valueIds: [1, 8],
    notes: "Sempre resolvendo com agilidade e colocando o cliente em primeiro lugar.",
    status: "entregue",
    createdAt: "2026-08-20T10:02:00Z",
    presentedAt: "2026-08-20T11:08:00Z",
  },
  {
    id: "entry-3",
    order: 3,
    editionId: "edition-2026-08",
    giver: "Luana Botica",
    receiver: "Luisa Lemos",
    valueIds: [5, 9],
    notes: "Parceria diária, trazendo leveza e sempre disposta a aprender e apoiar o time.",
    status: "entregue",
    createdAt: "2026-08-20T10:04:00Z",
    presentedAt: "2026-08-20T11:12:00Z",
  },
  {
    id: "entry-4",
    order: 4,
    editionId: "edition-2026-08",
    giver: "Thais",
    receiver: "Bianca Kim",
    valueIds: [4, 8],
    notes: "Design sensacional nas novas telas que emocionam nossos clientes!",
    status: "entregue",
    createdAt: "2026-08-20T10:05:00Z",
    presentedAt: "2026-08-20T11:15:00Z",
  },
  {
    id: "entry-5",
    order: 5,
    editionId: "edition-2026-08",
    giver: "Cromack",
    receiver: "Gustavo Soares",
    valueIds: [6, 3],
    notes: "Iniciativa monstra na refatoração da API e entrega rápida.",
    status: "entregue",
    createdAt: "2026-08-20T10:06:00Z",
    presentedAt: "2026-08-20T11:18:00Z",
  },
  {
    id: "entry-6",
    order: 6,
    editionId: "edition-2026-08",
    giver: "Sthephany Talasca",
    receiver: "Micaelle",
    valueIds: [7, 8],
    notes: "Humildade gigante para mentorar os novos nibers e dedicação sem igual.",
    status: "entregue",
    createdAt: "2026-08-20T10:07:00Z",
    presentedAt: "2026-08-20T11:21:00Z",
  },
  {
    id: "entry-7",
    order: 7,
    editionId: "edition-2026-08",
    giver: "Maris",
    receiver: "Luisa Lemos, Jéssica Conceição",
    valueIds: [8, 9],
    notes: "Equipe A+++ com sintonia fantástica e alegria constante nos rituais!",
    status: "falando", // Currently at mic
    createdAt: "2026-08-20T10:08:00Z",
  },
  {
    id: "entry-8",
    order: 8,
    editionId: "edition-2026-08",
    giver: "Sayuri",
    receiver: "Calebe",
    valueIds: [2, 3],
    notes: "Sonhando grande no projeto estratégico e executando com foco lean.",
    status: "fila",
    createdAt: "2026-08-20T10:09:00Z",
  },
  {
    id: "entry-9",
    order: 9,
    editionId: "edition-2026-08",
    giver: "Gabriel Gaspar",
    receiver: "Bia Rosa e time",
    valueIds: [1, 5],
    notes: "Melhoria diária no atendimento e feedback aos clientes.",
    status: "fila",
    createdAt: "2026-08-20T10:10:00Z",
  },
  {
    id: "entry-10",
    order: 10,
    editionId: "edition-2026-08",
    giver: "Bibia",
    receiver: "Catharina",
    valueIds: [7, 8],
    notes: "Exemplo de postura, competência técnica e humildade.",
    status: "fila",
    createdAt: "2026-08-20T10:12:00Z",
  },
  {
    id: "entry-11",
    order: 11,
    editionId: "edition-2026-08",
    giver: "Bianca Lisboa",
    receiver: "Mikaella Nicomedes",
    valueIds: [9, 8],
    notes: "Trabalhar com você é garantia de qualidade e boas risadas.",
    status: "fila",
    createdAt: "2026-08-20T10:14:00Z",
  },
  {
    id: "entry-12",
    order: 12,
    editionId: "edition-2026-08",
    giver: "Jéssica Barreiro",
    receiver: "Ivana Oliveira",
    valueIds: [1, 6],
    notes: "Proatividade pura em resolver os chamados críticos de clientes.",
    status: "fila",
    createdAt: "2026-08-20T10:15:00Z",
  },
  {
    id: "entry-13",
    order: 13,
    editionId: "edition-2026-08",
    giver: "Larissa Mota",
    receiver: "Say, Raquel e Brayan",
    valueIds: [8, 2, 9],
    notes: "Vocês são fenomenais! Time dos sonhos sonhando grande e entregando tudo.",
    status: "fila",
    createdAt: "2026-08-20T10:16:00Z",
  },

  // --- JULHO 2026 (PASSADA) ---
  {
    id: "entry-jul-1",
    order: 1,
    editionId: "edition-2026-07",
    giver: "Roberto Rocha",
    receiver: "Larissa Teixeira",
    valueIds: [3, 8],
    notes: "Organização impecável das metas trimestrais e ritmo do time.",
    status: "entregue",
    createdAt: "2026-07-16T10:00:00Z",
    presentedAt: "2026-07-16T11:00:00Z",
  },
  {
    id: "entry-jul-2",
    order: 2,
    editionId: "edition-2026-07",
    giver: "Gustavo Soares",
    receiver: "Gabriel Gaspar",
    valueIds: [1, 2],
    notes: "Liderança inspiradora e foco no crescimento sustentável.",
    status: "entregue",
    createdAt: "2026-07-16T10:05:00Z",
    presentedAt: "2026-07-16T11:04:00Z",
  },
  {
    id: "entry-jul-3",
    order: 3,
    editionId: "edition-2026-07",
    giver: "Calebe",
    receiver: "Time de Suporte Nibo",
    valueIds: [1, 9],
    notes: "Atendimento com nota 10 dos clientes e clima sempre leve!",
    status: "entregue",
    createdAt: "2026-07-16T10:10:00Z",
    presentedAt: "2026-07-16T11:09:00Z",
  },
  {
    id: "entry-jul-4",
    order: 4,
    editionId: "edition-2026-07",
    giver: "Bianca Kim",
    receiver: "Thais",
    valueIds: [4, 5],
    notes: "Parceria criativa no fluxo de onboarding e UX incrível.",
    status: "entregue",
    createdAt: "2026-07-16T10:15:00Z",
    presentedAt: "2026-07-16T11:14:00Z",
  },
  {
    id: "entry-jul-5",
    order: 5,
    editionId: "edition-2026-07",
    giver: "Catharina",
    receiver: "Bibia",
    valueIds: [7, 8],
    notes: "Pela generosidade e suporte nos fechamentos contábeis.",
    status: "entregue",
    createdAt: "2026-07-16T10:20:00Z",
    presentedAt: "2026-07-16T11:18:00Z",
  },

  // --- JUNHO 2026 (PASSADA) ---
  {
    id: "entry-jun-1",
    order: 1,
    editionId: "edition-2026-06",
    giver: "Jéssica Conceição",
    receiver: "Maris",
    valueIds: [8, 9],
    notes: "Pela alegria e condução impecável das reuniões gerais!",
    status: "entregue",
    createdAt: "2026-06-18T10:00:00Z",
    presentedAt: "2026-06-18T11:00:00Z",
  },
  {
    id: "entry-jun-2",
    order: 2,
    editionId: "edition-2026-06",
    giver: "Luisa Lemos",
    receiver: "Luana Botica",
    valueIds: [5, 6],
    notes: "Pelo aprendizado mútuo e coragem para inovar nos fluxos.",
    status: "entregue",
    createdAt: "2026-06-18T10:05:00Z",
    presentedAt: "2026-06-18T11:05:00Z",
  },
  {
    id: "entry-jun-3",
    order: 3,
    editionId: "edition-2026-06",
    giver: "Ivana Oliveira",
    receiver: "Jéssica Barreiro",
    valueIds: [1, 3],
    notes: "Execução rápida e carinho enorme com cada cliente da Nibo.",
    status: "entregue",
    createdAt: "2026-06-18T10:10:00Z",
    presentedAt: "2026-06-18T11:10:00Z",
  },
];

export const INITIAL_EDITION = INITIAL_EDITIONS[0];
